### ISSUE TITLE
Problems Testing 

### ISSUE THREAD

**Issue by automacaosamos** [GitStorageOne/mORMot.REST#1]
I installed the following example certificates step by step
But when I select the # _https_ option it gives these messages:
20170808 15095033  +    mORMotHttpServer.TSQLHttpServer(03316910).0076D98F 
20170808 15095033 http  	mORMotHttpServer.TSQLHttpServer(03316910) {"THttpServer(0328CD20)":{"ServerConnectionCount":1,"ServerKeepAliveTimeOut":3000,"TCPPrefix":"","ThreadPool":{"TSynThreadPoolTHttpServer(03376CC0)":{"HeaderErrors":1,"HeaderProcessed":0,"BodyProcessed":0,"BodyOwnThreads":0,"RunningThreads":32}},"ThreadPoolContentionCount":0,"ThreadPoolContentionAbortCount":0,"APIVersion":"WinSock 2.0.514","ServerName":"mORMot (Windows)","ProcessName":"service "}} finalized for 1 server

**Comment by automacaosamos** [comment]
I am new to mormot, would a simple example be possible only with HTTPS? to learn

**Comment by GitStorageOne** [comment]
Hello.
Does that happen even if you start server as administrator? (using right mouse click).

**Comment by automacaosamos** [comment]
Yes I run as administrator, I installed the sample certificate,

**Comment by automacaosamos** [comment]
My private email: suporte@samos.com.br, if you wish, I can send the screens to you

**Comment by GitStorageOne** [comment]
I reproduced issue on one PC (with latest win 10), in same time, everything work fine on another PC (not latest windows 10).
Let me know, which delphi version and OS (run cmd to see version string) do you use.
Also, try another network port.

Seems in win10 creator update [something changed with dll load](https://community.embarcadero.com/article/16556-rad-studio-10-2-1-released-today).
Latest delphi 10.2.1 include:
> A significant issue we fixed on Windows was changing our compilers and linkers to address an OS level change on Windows 10 Creators Update affecting the way the operating system loads DLLs.

So, i'm going to update delphi to latest build and check what will happen.

**Comment by automacaosamos** [comment]
Thank you so much for helping me, I need you so much.
My windows are:
Microsoft Windows [version 10.0.15063]
My Delphi is Tokyo:
Embarcadero® Delphi 10.2

Cido

**Comment by automacaosamos** [comment]
I did a test in windows 2016 worked perfectly, the problem is in windows 10.

thanks.

**Comment by GitStorageOne** [comment]
I tested project under delphi 10.2.1.
Seems, same issue, then i found that same port (777) already taken by another application.
You can check that in cmd: netsh http show urlacl
When i deleted old binding, started server as admin - everything works fine.

Note, if you want use another port with SSL, you must edit file install-and-register-certs_run-as-admin.bat
First line contain required port number.

**Comment by automacaosamos** [comment]
Worked perfect
thank you.
