### ISSUE TITLE
how to call service in web browser with parameters ?

### ISSUE THREAD

**Issue by linbren** [GitStorageOne/mORMot.REST#2]
with no param, it could be call as bellow:
http://localhost:777/service/RestMethods.HelloWorld?session_signature=1B172DA500A64255E8530950

how to call them with parameters such as  : (I'd like to sum up 1 and 2)
http://localhost:777/service/RestMethods.Sum?session_signature=1B172DA500A643E99B88A0D8&val1=1&val=2

**Comment by linbren** [comment]
besides ,how submit records set as parameter ?

**Comment by GitStorageOne** [comment]
Try this: 
https://synopse.info/files/html/Synopse%20mORMot%20Framework%20SAD%201.18.html#TITLE_448
https://synopse.info/files/html/Synopse%20mORMot%20Framework%20SAD%201.18.html#TITLE_452

Also, you can install free apache JMeter. My source code include *.jmx scripts that show how to send records as json values via request body.

**Comment by linbren** [comment]
thank you , found the solution .
