### ISSUE TITLE
How to create SSL certificate

### ISSUE THREAD

**Issue by automacaosamos** [GitStorageOne/mORMot.REST#3]
Sorry for the inconvenience, I have no experience in mormot / https
I created my own certificate and installed it, as below
But it does not work, how did you generate your certificate?

C:\Windows\system32>SET SSLPort=777
C:\Windows\system32>certutil -f -importpfx "C:\mORMot.REST\enable_https\prudenmoveis.com.br.pfx"
Enter password PFX:
Certificate "prudenmoveis.com.br" add from repository
Certificate "prudenmoveis.com.br" Added to the repository.
CertUtil: -importPFX : ompleted successfully..
C:\Windows\system32>netsh http add sslcert ipport=0.0.0.0:777 certhash=f3827b539b017269c97f9aef84d0df5bf09af716 appid={30B74F5C-732D-4398-8FE4-184AC98FD0AF}
SSL certificate added successfully
C:\Windows\system32>pause
Press any key to continue. . .

message in mORMotRESTcl.exe

20170814 16322238 warn  	mORMotHttpClient.TSQLHttpClientWinHTTP(032B2AB0) /TimeStamp call failed -> Server not available
20170814 16322238  -    00.042.403
20170814 16322238  +    mORMotHttpClient.TSQLHttpClientWinHTTP(032B2AB0).CallBackGet service/TimeStamp
20170814 16322238  +    	mORMotHttpClient.TSQLHttpClientWinHTTP(032B2AB0).00752178 
20170814 16322238 EXC   		EWinHTTP ("WinHTTP security error. Status 65536, statusInfo: 16") at 007388DC  stack trace API 006622A7 006622D0 0040B004 
20170814 16322238  -    	00.001.876
20170814 16322238  -    00.001.889
20170814 16322238 warn  mORMotHttpClient.TSQLHttpClientWinHTTP(032B2AB0) /TimeStamp call failed -> Server not available

**Comment by GitStorageOne** [comment]
Hello. I used this software for certificate management: https://sourceforge.net/projects/xca/
You included client side log, but what about server side? Did you started server with https mode?
Your appid is different, did you updated constant in source code?

**Comment by automacaosamos** [comment]
Hello!!
 Yes I started server and client in mode https, run as administrator and enable LOG in client and server
Sorry, what constant do I need to update ??

I not undertand.

thanks

**Comment by GitStorageOne** [comment]
Forget about that. Can you include server log?

**Comment by automacaosamos** [comment]
My Server LOG
20170814 20133347 warn  mORMot.TSQLRestServerFullMemory(035EFD70) TSQLRestServerFullMemory.AfterDeleteForceCoherency() failed to handle field TSQLAuthUser.GroupRights
20170814 20133347  +    mORMotHttpServer.TSQLHttpServer(035F6870).Create useHttpApiRegisteringURI (secSSL) on port 777
20170814 20133347 http  	mORMotHttpServer.TSQLHttpServer(035F6870) http.sys registration of https://+:777/service
20170814 20133347 info  SetThreadName 00001714=TSQLHttpServer 777/service THttpApiServer
20170814 20133347 trace mORMot.TSQLRestServerFullMemory(035EFD70) BeginCurrentThread(THttpApiServer) root=service ThreadID=00001714 ThreadCount=1
20170814 20133347 info  SetThreadName 00000854=TSQLHttpServer 777/service THttpApiServer
20170814 20133347 trace mORMot.TSQLRestServerFullMemory(035EFD70) BeginCurrentThread(THttpApiServer) root=service ThreadID=00000854 ThreadCount=2
20170814 20133347 info  SetThreadName 00002FAC=TSQLHttpServer 777/service THttpApiServer
20170814 20133347 trace mORMot.TSQLRestServerFullMemory(035EFD70) BeginCurrentThread(THttpApiServer) root=service ThreadID=00002FAC ThreadCount=3
20170814 20133347 info  SetThreadName 000004B4=TSQLHttpServer 777/service THttpApiServer
20170814 20133347 trace mORMot.TSQLRestServerFullMemory(035EFD70) BeginCurrentThread(THttpApiServer) root=service ThreadID=000004B4 ThreadCount=4
20170814 20133347 info  SetThreadName 000010C0=TSQLHttpServer 777/service THttpApiServer
20170814 20133347 trace mORMot.TSQLRestServerFullMemory(035EFD70) BeginCurrentThread(THttpApiServer) root=service ThreadID=000010C0 ThreadCount=5
20170814 20133347 info  SetThreadName 000025C8=TSQLHttpServer 777/service THttpApiServer
20170814 20133347 trace mORMot.TSQLRestServerFullMemory(035EFD70) BeginCurrentThread(THttpApiServer) root=service ThreadID=000025C8 ThreadCount=6
20170814 20133347 info  SetThreadName 00002708=TSQLHttpServer 777/service THttpApiServer
20170814 20133347 trace mORMot.TSQLRestServerFullMemory(035EFD70) BeginCurrentThread(THttpApiServer) root=service ThreadID=00002708 ThreadCount=7
20170814 20133347 info  SetThreadName 00000A14=TSQLHttpServer 777/service THttpApiServer
20170814 20133347 trace mORMot.TSQLRestServerFullMemory(035EFD70) BeginCurrentThread(THttpApiServer) root=service ThreadID=00000A14 ThreadCount=8
20170814 20133347 info  SetThreadName 00000828=TSQLHttpServer 777/service THttpApiServer
20170814 20133347 trace mORMot.TSQLRestServerFullMemory(035EFD70) BeginCurrentThread(THttpApiServer) root=service ThreadID=00000828 ThreadCount=9
20170814 20133347 info  SetThreadName 00002244=TSQLHttpServer 777/service THttpApiServer
20170814 20133347 trace mORMot.TSQLRestServerFullMemory(035EFD70) BeginCurrentThread(THttpApiServer) root=service ThreadID=00002244 ThreadCount=10
20170814 20133347 info  SetThreadName 000029F4=TSQLHttpServer 777/service THttpApiServer
20170814 20133347 trace mORMot.TSQLRestServerFullMemory(035EFD70) BeginCurrentThread(THttpApiServer) root=service ThreadID=000029F4 ThreadCount=11
20170814 20133347 info  SetThreadName 00001934=TSQLHttpServer 777/service THttpApiServer
20170814 20133347 trace mORMot.TSQLRestServerFullMemory(035EFD70) BeginCurrentThread(THttpApiServer) root=service ThreadID=00001934 ThreadCount=12
20170814 20133347 info  SetThreadName 00002A50=TSQLHttpServer 777/service THttpApiServer
20170814 20133347 trace mORMot.TSQLRestServerFullMemory(035EFD70) BeginCurrentThread(THttpApiServer) root=service ThreadID=00002A50 ThreadCount=13
20170814 20133347 info  SetThreadName 00002344=TSQLHttpServer 777/service THttpApiServer
20170814 20133347 trace mORMot.TSQLRestServerFullMemory(035EFD70) BeginCurrentThread(THttpApiServer) root=service ThreadID=00002344 ThreadCount=14
20170814 20133347 info  SetThreadName 00002F44=TSQLHttpServer 777/service THttpApiServer
20170814 20133347 trace mORMot.TSQLRestServerFullMemory(035EFD70) BeginCurrentThread(THttpApiServer) root=service ThreadID=00002F44 ThreadCount=15
20170814 20133347 info  SetThreadName 00002B68=TSQLHttpServer 777/service THttpApiServer
20170814 20133347 trace mORMot.TSQLRestServerFullMemory(035EFD70) BeginCurrentThread(THttpApiServer) root=service ThreadID=00002B68 ThreadCount=16
20170814 20133347 info  SetThreadName 00000A1C=TSQLHttpServer 777/service THttpApiServer
20170814 20133347 trace mORMot.TSQLRestServerFullMemory(035EFD70) BeginCurrentThread(THttpApiServer) root=service ThreadID=00000A1C ThreadCount=17
20170814 20133347 info  SetThreadName 00002A20=TSQLHttpServer 777/service THttpApiServer
20170814 20133347 trace mORMot.TSQLRestServerFullMemory(035EFD70) BeginCurrentThread(THttpApiServer) root=service ThreadID=00002A20 ThreadCount=18
20170814 20133347 info  SetThreadName 00002AA0=TSQLHttpServer 777/service THttpApiServer
20170814 20133347 trace mORMot.TSQLRestServerFullMemory(035EFD70) BeginCurrentThread(THttpApiServer) root=service ThreadID=00002AA0 ThreadCount=19
20170814 20133347 info  SetThreadName 000013C0=TSQLHttpServer 777/service THttpApiServer
20170814 20133347 trace mORMot.TSQLRestServerFullMemory(035EFD70) BeginCurrentThread(THttpApiServer) root=service ThreadID=000013C0 ThreadCount=20
20170814 20133347 info  SetThreadName 000020C8=TSQLHttpServer 777/service THttpApiServer
20170814 20133347 trace mORMot.TSQLRestServerFullMemory(035EFD70) BeginCurrentThread(THttpApiServer) root=service ThreadID=000020C8 ThreadCount=21
20170814 20133347 info  SetThreadName 00002E1C=TSQLHttpServer 777/service THttpApiServer
20170814 20133347 trace mORMot.TSQLRestServerFullMemory(035EFD70) BeginCurrentThread(THttpApiServer) root=service ThreadID=00002E1C ThreadCount=22
20170814 20133347 info  SetThreadName 00001F64=TSQLHttpServer 777/service THttpApiServer
20170814 20133347 trace mORMot.TSQLRestServerFullMemory(035EFD70) BeginCurrentThread(THttpApiServer) root=service ThreadID=00001F64 ThreadCount=23
20170814 20133347 info  SetThreadName 00000894=TSQLHttpServer 777/service THttpApiServer
20170814 20133347 trace mORMot.TSQLRestServerFullMemory(035EFD70) BeginCurrentThread(THttpApiServer) root=service ThreadID=00000894 ThreadCount=24
20170814 20133347 info  SetThreadName 000007E0=TSQLHttpServer 777/service THttpApiServer
20170814 20133347 trace mORMot.TSQLRestServerFullMemory(035EFD70) BeginCurrentThread(THttpApiServer) root=service ThreadID=000007E0 ThreadCount=25
20170814 20133347 info  SetThreadName 00001EA8=TSQLHttpServer 777/service THttpApiServer
20170814 20133347 trace mORMot.TSQLRestServerFullMemory(035EFD70) BeginCurrentThread(THttpApiServer) root=service ThreadID=00001EA8 ThreadCount=26
20170814 20133347 info  SetThreadName 00001768=TSQLHttpServer 777/service THttpApiServer
20170814 20133347 trace mORMot.TSQLRestServerFullMemory(035EFD70) BeginCurrentThread(THttpApiServer) root=service ThreadID=00001768 ThreadCount=27
20170814 20133347 info  SetThreadName 0000204C=TSQLHttpServer 777/service THttpApiServer
20170814 20133347 trace mORMot.TSQLRestServerFullMemory(035EFD70) BeginCurrentThread(THttpApiServer) root=service ThreadID=0000204C ThreadCount=28
20170814 20133347 info  SetThreadName 00002A98=TSQLHttpServer 777/service THttpApiServer
20170814 20133347 trace mORMot.TSQLRestServerFullMemory(035EFD70) BeginCurrentThread(THttpApiServer) root=service ThreadID=00002A98 ThreadCount=29
20170814 20133347 info  SetThreadName 000007D0=TSQLHttpServer 777/service THttpApiServer
20170814 20133347 trace mORMot.TSQLRestServerFullMemory(035EFD70) BeginCurrentThread(THttpApiServer) root=service ThreadID=000007D0 ThreadCount=30
20170814 20133347 info  SetThreadName 00002EA0=TSQLHttpServer 777/service THttpApiServer
20170814 20133347 trace mORMot.TSQLRestServerFullMemory(035EFD70) BeginCurrentThread(THttpApiServer) root=service ThreadID=00002EA0 ThreadCount=31
20170814 20133347 http  	mORMotHttpServer.TSQLHttpServer(035F6870) {"THttpApiServer(0361D1F0)":{"Cloned":false,"RegisteredUrl":"https://+:777/service/","HTTPQueueLength":1000,"MaxBandwidth":-1,"MaxConnections":-1,"APIVersion":"HTTP API 2.0","ServerName":"mORMot (Windows)","ProcessName":"service "}} initialized for service
20170814 20133347 info  SetThreadName 00000860=TSQLHttpServer 777/service THttpApiServer
20170814 20133347  -    00.004.017
20170814 20133347 trace mORMot.TSQLRestServerFullMemory(035EFD70) BeginCurrentThread(THttpApiServer) root=service ThreadID=00000860 ThreadCount=32

**Comment by automacaosamos** [comment]
My Client LOG
20170814 20153615  +    mORMotHttpClient.TSQLHttpClientWinHTTP(03202AB0).CallBackGet service/Auth?UserName=George
20170814 20153615  +    	mORMotHttpClient.TSQLHttpClientWinHTTP(03202AB0).CallBackGet service/TimeStamp
20170814 20153615  +    		mORMotHttpClient.TSQLHttpClientWinHTTP(03202AB0).00752178 
20170814 20153617 EXC   			EWinHTTP ("WinHTTP security error. Status 65536, statusInfo: 16") at 007388DC  stack trace API 006622A7 006622D0 0040B004 
20170814 20153617  -    		00.023.270
20170814 20153617  -    	00.023.549
20170814 20153617 warn  	mORMotHttpClient.TSQLHttpClientWinHTTP(03202AB0) /TimeStamp call failed -> Server not available
20170814 20153617  -    00.023.559
20170814 20153617  +    mORMotHttpClient.TSQLHttpClientWinHTTP(03202AB0).CallBackGet service/TimeStamp
20170814 20153617  +    	mORMotHttpClient.TSQLHttpClientWinHTTP(03202AB0).00752178 
20170814 20153617 EXC   		EWinHTTP ("WinHTTP security error. Status 65536, statusInfo: 16") at 007388DC  stack trace API 006622A7 006622D0 0040B004 
20170814 20153617  -    	00.001.598
20170814 20153617  -    00.001.610
20170814 20153617 warn  mORMotHttpClient.TSQLHttpClientWinHTTP(03202AB0) /TimeStamp call failed -> Server not available

**Comment by automacaosamos** [comment]
My certificate and bats.

:: Define SSL port
SET SSLPort=777

:: Install certs
:: You can use certlm.msc to ensure that sertificates was added.
certutil -f -importpfx "%~dp0prudenmoveis.com.br.pfx"

:: Add SSL port
:: You can use "netsh http show sslcert" to ensure that port was added.
netsh http add sslcert ipport=0.0.0.0:%SSLPort% certhash=f3827b539b017269c97f9aef84d0df5bf09af716 appid={30B74F5C-732D-4398-8FE4-184AC98FD0AF}

pause
thanks

**Comment by GitStorageOne** [comment]
I'm really not sure what is wrong :)
As i understand, everything fine when you use my certificate.
"WinHTTP security error", suppose that your certificate not include private key for encryption.
Try xca utility (create new private key and cert), then use *.p12 export format.

**Comment by automacaosamos** [comment]
Ok it may be this, I'll try, 
thank you

**Comment by automacaosamos** [comment]
I generated the certificate from a 10 different ways using the XCA, and it did not work, could it show me the steps screen of how you generated it?

Thank you.

**Comment by automacaosamos** [comment]
Hello after many different attempts I was able to generate the certificate for my tests

Thank you for your attention, it helped a lot.
